name: CI

on:
  push:
    branches: [ "master", "vcpkg" ]
  pull_request:
    branches: [ "master", "vcpkg" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      restore_export:
        description: 'Restore vcpkg export from cache'
        type: boolean
        default: true
      target_pattern:
        description: 'Build jobs matching this pattern'
        type: string
        default: "^"

  # Keep cache alive
  schedule:
    - cron: '10 21 * * 2,5'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  arm64-android:
    if: ${{ contains('^arm64-android$', inputs.target_pattern) }}
    uses: dg0yt/mapper/.github/workflows/vcpkg.yml@vcpkg
    with:
      runner: ubuntu-24.04
      target-triplet: arm64-android-dynamic-release
      host-triplet: x64-linux-dynamic-release
      restore_export: ${{ inputs.restore_export != 'false' }}
      cmake-args: "--trace"
    secrets:
      ARTIFACTS_KEY: ${{ secrets.ARTIFACTS_KEY }}

  arm64-macos:
    if: ${{ contains('^arm64-macos$', inputs.target_pattern) }}
    uses: dg0yt/mapper/.github/workflows/vcpkg.yml@vcpkg
    with:
      runner: macos-15
      target-triplet: arm64-osx-dynamic-release
      host-triplet: arm64-osx-dynamic-release
      restore_export: ${{ inputs.restore_export != 'false' }}
      cmake-args: "-DMapper_SYSTEM_NAME=macOS-arm64"
    secrets:
      ARTIFACTS_KEY: ${{ secrets.ARTIFACTS_KEY }}

  x64-linux:
    if: ${{ contains('^x64-linux$', inputs.target_pattern) }}
    uses: dg0yt/mapper/.github/workflows/vcpkg.yml@vcpkg
    with:
      runner: ubuntu-24.04
      target-triplet: x64-linux-dynamic-release
      host-triplet: x64-linux-dynamic-release
      restore_export: ${{ inputs.restore_export != 'false' }}
    secrets:
      ARTIFACTS_KEY: ${{ secrets.ARTIFACTS_KEY }}

  x64-linux-debug:
    if: ${{ contains('^x64-linux-debug$', inputs.target_pattern) }}
    uses: dg0yt/mapper/.github/workflows/vcpkg.yml@vcpkg
    with:
      runner: ubuntu-24.04
      target-triplet: x64-linux-dynamic-release
      host-triplet: x64-linux-dynamic-release
      restore_export: ${{ inputs.restore_export != 'false' }}
      cmake-args: -DCMAKE_BUILD_TYPE=Debug
    secrets:
      ARTIFACTS_KEY: ${{ secrets.ARTIFACTS_KEY }}

  x64-macos:
    if: ${{ contains('^x64-macos$', inputs.target_pattern) }}
    uses: dg0yt/mapper/.github/workflows/vcpkg.yml@vcpkg
    with:
      runner: macos-15-intel
      target-triplet: x64-osx-dynamic-release
      host-triplet: x64-osx-dynamic-release
      restore_export: ${{ inputs.restore_export != 'false' }}
      cmake-args: "-DMapper_SYSTEM_NAME=macOS-x64"
    secrets:
      ARTIFACTS_KEY: ${{ secrets.ARTIFACTS_KEY }}

  x64-windows:
    if: ${{ contains('^x64-windows$', inputs.target_pattern) }}
    uses: dg0yt/mapper/.github/workflows/vcpkg.yml@vcpkg
    with:
      runner: windows-2025-vs2026
      target-triplet: x64-windows-dynamic-release
      host-triplet: x64-windows-dynamic-release
      restore_export: ${{ inputs.restore_export != 'false' }}
      cmake-args: "-DVCPKG_CRT_LINKAGE=dynamic -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl"
    secrets:
      ARTIFACTS_KEY: ${{ secrets.ARTIFACTS_KEY }}
