name: GHA security analysis (zizmor)

on:
  push:
    branches: [ "master", "vcpkg" ]
    paths: .github
  pull_request:
    branches: [ "master", "vcpkg" ]
    paths: .github
  workflow_dispatch:

permissions: {}

jobs:
  zizmor:
    name: GHA security analysis (zizmor)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: false

      - name: Run zizmor
        run: uvx zizmor --format=github .
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
